# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807a6d977bf172f6ce1ad0c227654e0c38602b21bb7434dc85105ae45db61de608309e07114c43bb91cd19bfd25774491a61620f5090b7f268ace44d30e7472b

test:
  secret_key_base: 665278eccd93c6dd7721e27e6079747495a24c644feeb607392f351823848c7d2c2e0fc55e97a71a7697218b23b233675ba5bf9adaa0df4081e69560e2bfaa6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
